### ISSUE TITLE
MR ne s'affiche pas dans les modes de livraison

### ISSUE THREAD

**Issue by valentin3522** [thelia-modules/MondialRelay#3]
Malgré isValidDelivery(Country $country)  {          return true;           }, impossible d'afficher MR dans les modes de livraison dans le front. 

Zones de livraison (France en l'occurence) correctement configuré...

**Comment by roadster31** [comment]
Corrigé par la release 1.0.6 : https://github.com/thelia-modules/MondialRelay/releases/tag/1.0.6
